version: '3.9'

services:
  tests:
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    environment:
      SERVER_URL: http://localhost:5215
      STAGE: all
    
  