// <auto-generated />
using System;
using DripChip_API.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DripChipAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnimalTypes", b =>
                {
                    b.Property<long>("animalTypesid")
                        .HasColumnType("bigint");

                    b.Property<long>("animalsid")
                        .HasColumnType("bigint");

                    b.HasKey("animalTypesid", "animalsid");

                    b.HasIndex("animalsid");

                    b.ToTable("AnimalTypes");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.Animal", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<int>("chipperId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("chippingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("chippingLocationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("deathDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("height")
                        .HasColumnType("real");

                    b.Property<float>("length")
                        .HasColumnType("real");

                    b.Property<string>("lifeStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("weight")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.Location", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.HasKey("id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.LocationInfo", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<long>("animalid")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("dateTimeOfVisitLocationPoint")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("locationPointid")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("animalid");

                    b.HasIndex("locationPointid");

                    b.ToTable("LocationInfo");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.Types", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("id"));

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AnimalTypes", b =>
                {
                    b.HasOne("DripChip_API.Domain.Models.Types", null)
                        .WithMany()
                        .HasForeignKey("animalTypesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DripChip_API.Domain.Models.Animal", null)
                        .WithMany()
                        .HasForeignKey("animalsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.LocationInfo", b =>
                {
                    b.HasOne("DripChip_API.Domain.Models.Animal", "animal")
                        .WithMany("visitedLocations")
                        .HasForeignKey("animalid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DripChip_API.Domain.Models.Location", "locationPoint")
                        .WithMany()
                        .HasForeignKey("locationPointid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("animal");

                    b.Navigation("locationPoint");
                });

            modelBuilder.Entity("DripChip_API.Domain.Models.Animal", b =>
                {
                    b.Navigation("visitedLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
